### ISSUE TITLE
support `Shiki` transformers

### ISSUE THREAD

**Issue by cpreston321** [pi0/nuxt-shiki#4]
# Transformers

- [twoslash](https://shiki.style/packages/twoslash)
  - Example: https://github.com/antfu/nuxt-content-twoslash

**Comment by pi0** [comment]
`shiki.highlight` (API in `nuxt-shiki`) allows `transformers` to be passed (via programmatic also component) in 0.2+

I think it should be enough to unblock any higher order usages of this module to include transformers. 

Additionally we could support a plugin hook to allow extending default transforms. I think specially since this module could be used by multiple modules, global mutations are inheritingly a dangerous territory.
